### ISSUE TITLE
Alientube breaks "Read More" button on longer YouTube comments

### ISSUE THREAD

**Issue by Razer1103** [xlexi/alientube#154] opened 2015-08-12 17:12 UTC
Long comments instead stop abruptly, the text is there but hidden, with no way to unhide it as there should be ordinarily.

**Comment by xlexi** [comment] 2015-08-20 08:22
Hello, I am unable to reproduce this issue, what browser are you using?

**Comment by Carnivaling** [comment] 2015-08-23 23:45
This has been happening to me, too, in chrome. It seems to happen mainly with long paragraphs of text (see: http://puu.sh/jM9wF/4a5b23ad07.png). But, the read more button kept disappearing and reappearing for this one: http://puu.sh/jM9uI/5a032b4f20.png every time I refreshed the page. It was kind of random.

**Comment by Razer1103** [comment] 2015-08-29 00:51
Hi, sorry, I forgot to reply to this until now. Currently I'm running Chrome Version 44.0.2403.155 m (64-bit). I've also observed the issue on some previous versions of chrome too. Carnivaling is right, the read more button SOMETIMES appears, but sometimes not. For me, the comments are not cut off in the middle of a line.

**Comment by HyphenSam** [comment] 2015-09-20 08:06
I am also having this issue. I am using Firefox version 40.0.3

With AlienTube disabled: https://i.imgur.com/Rb5F3BW.png
With AlienTube enabled: https://i.imgur.com/lztTt13.png

**Comment by xlexi** [comment] 2015-10-13 23:11
Good news everyone, I finally found out what caused this, it was the way Google+ comments was being hidden. It has been fixed and will be in the next update

**Closed** 2015-10-13 23:11 UTC
Labels: bug
