### ISSUE TITLE
Google+ comments don't have a "Read more" button anymore

### ISSUE THREAD

**Issue by TerraBubble** [xlexi/alientube#123] opened 2015-04-26 00:59 UTC
I love this extension, btw.

It appears to have broken google+ plus comments slightly though - when a comment is too long and you need to click the "Read more" button, that button is now missing (resulting in what look like half finished comments).

When I disable AlienTube, the read more button comes back ( but the reddit disappears D: )

Thanks!

**Comment by xlexi** [comment] 2015-04-26 06:32
Hello, I am unable to reproduce this. What browser are you using? Also can you give me a link to one of the videos where this is happening for you

**Comment by xlexi** [comment] 2015-05-03 12:20
Since you find yourself unable to respond and I cannot reproduce I will have to close this, please create a new issue if you encounter the problem again.

**Closed by xlexi** 2015-05-03 12:20 UTC
Labels: invalid
